from .facultad_service import FacultadService
from .universidad_service import UniversidadService
from .autoridad_service import AutoridadService
from .facultad_service import FacultadService
from .plan_service import PlanService
from .grupo_service import GrupoService
from .especilidad_service import EspecialidadService
from .tipoespecialidad_service import TipoespecialidadService
from .cargo_service import CargoService
from .departamento_service import DepartamentoService
from .grado_service import GradoService
from .orientacion_service import OrientacionService
from .categoria_cargo_service import CategoriaCargoService
from .alumno_service import AlumnoService
from .area_service import AreaService
from .materia_service import MateriaService
from .tipoDedicacionService import TipoDedicacionService
from .usuario_service import UsuarioService
from .nota_service import NotaService
from .tipodocumento_service import TipoDocumentoService
from .documentos_office_service import Documents, PDFDocument, ODTDocument, DOCXDocument