from .home import home 
from .certificado_resources import certificado_bp
from .universidad_resource import universidad_bp 
from .cargo_resource import cargo_bp
from .categoria_cargo_resource import categoria_cargo_bp
from .materia_resource import materia_bp
from .autoridad_resource import autoridad_bp
from .tipo_dedicacion_resource import tipo_dedicacion_bp
from .especialidad_resource import especialidad_bp
from .tipo_especialidad_resource import tipo_especialidad_bp    
from .grupo_resource import grupo_bp 
from .usuario_resource import usuario_bp   
from .facultad_resource import facultad_bp
from .departamento_resource import departamento_bp
from .grado_resource import grado_bp
from .orientacion_resource import orientacion_bp
from .plan_resources import plan_bp
