from .universidad import Universidad
from .facultad import Facultad
from .autoridad import Autoridad
from .especialidad import Especialidad
from .plan import Plan
from .materia import Materia
from .orientacion import Orientacion
from .alumno import Alumno
from .tipoEspecialidad import TipoEspecialidad
from .orientacion import Orientacion
from .grado import Grado
from .departamento import Departamento
from .cargo import Cargo
from .area import Area
from .grupo import Grupo
from .usuario import Usuario
from .nota import Nota
from .categoria_cargo import CategoriaCargo
from .tipoDedicacion import TipoDedicacion
from .tipoDocumento import TipoDocumento
from .plan_materia import PlanMateria
